PackageIdentifier: WinZip.WinZip
PackageVersion: 7.6.0
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://raw.githubusercontent.com/sashankku/WingetRepo/main/installers/winzip76.exe
    InstallerSha256: B9C54457A260A168FA0EB60F2AE1A5C7A5B7072A8120E37E9561FAD6F914E298
    Scope: machine
    MinimumOSVersion: 10.0.0.0
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
      Custom: /D=C:\Winzip
ManifestType: installer
ManifestVersion: 1.6.0